### ISSUE TITLE
Account status, balances

### ISSUE THREAD

**Issue by klepsydra** [wakproductions/tdameritrade_api#2]
Hi Winston @wakproductions ,

Preferring Ruby, I will attempt to add things like account status/balances/positions/orders etc. and eventually trading, in my fork.  Unless there is already some duplicated effort?

**Comment by wakproductions** [comment]
That would be awesome! I have not been working on those aspects since I have all the functionality I need on a daily basis for scans. If you add those features, please be sure to include tests. I have been thinking about using the VCR gem to mock the HTTP responses for future tests.

**Comment by naren8642** [comment]
I was interested in this but I am also exploring other options right now. But if there is someone else also working on it, I would love to collaborate!

**Comment by naren8642** [comment]
I have submitted a pull request with my order management code.

**Comment by wakproductions** [comment]
Here's a mocking library you could possibly use to mimic the API calls https://github.com/realestate-com-au/pact
